[build-system]
# Minimum requirements for the build system to execute.
requires = [
    'setuptools >=49.6.0',
'sage-setup ~= 10.1b3',
'pkgconfig >=1.5.1',
'sagemath-environment ~= 10.1b3',
'sagemath-categories ~= 10.1b3',
'cython >=0.29.21, <1.0',
'gmpy2 >=2.1.0',
'cysignals >=1.10.2',
'memory_allocator',
]
build-backend = "setuptools.build_meta"
