[build-system]
build-backend = 'mesonpy'
requires = [
    'meson-python',
    'cython >=3.0, != 3.0.3',
    'numpy >=1.19',
    'cypari2 >=2.1.1',
    'cysignals >=1.10.2',
    'gmpy2 >=2.1.0',
    'memory_allocator'
]

[project]
name = 'sagemath'
dynamic = ["version"]
