name: CI Linux

on:
  push:
    tags:
      - '*'
  # TODO: Remove this before merging
  pull_request:
  workflow_dispatch:
    # Allow to run manually

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:trusty
          - ubuntu:xenial
          - ubuntu:bionic
          - ubuntu:focal
          - ubuntu:jammy
          - ubuntu:lunar
          - ubuntu:mantic
          - debian:buster
          - debian:bullseye
          - debian:bookworm
          - debian:trixie
          - debian:sid
          - linuxmintd/mint20.1
          - linuxmintd/mint20.2
          - linuxmintd/mint20.3
          - linuxmintd/mint21
          - linuxmintd/mint21.1
          - linuxmintd/mint21.2
          - fedora:30
          - fedora:31
          - fedora:32
          - fedora:33
          - fedora:34
          - fedora:35
          - fedora:36
          - fedora:37
          - fedora:38
          - fedora:39
          - centos:centos7
          - quay.io/centos/centos:stream8
          - quay.io/centos/centos:stream9
          - almalinux:8
          - almalinux:9
          - sheerluck/sage-on-gentoo-stage4
          - archlinux
          - opensuse/leap:15.3
          - opensuse/leap:15.4
          - opensuse/leap:15.5
          - opensuse/tumbleweed
          - i386/ubuntu:bionic
          - i386/debian:bullseye
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Python version
        run: |
          echo "install_python=$(python -c 'import sys; print(sys.version_info < (3, 9))'" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        if: ${{ env.install_python }}
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          eval $(build/bin/sage-print-system-package-command auto update)
          eval $(build/bin/sage-print-system-package-command auto --yes install $(build/bin/sage-get-system-packages auto $(build/bin/sage-package list :standard:)))

      - name: Bootstrap
        run: python -m sage_setup.autogen.interpreters src/sage/ext/interpreters
        env:
          PYTHONPATH: src

      - name: Build
        run: pip install --no-build-isolation --config-settings=builddir=builddir . -v

      - name: Test
        run: ./sage -t --all -p4 || true
        