name: Build documentation

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_ci_fixes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Merge CI fixes from sagemath/sage
        run: |
          .ci/merge-fixes.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Store CI fixes in upstream artifact
        run: |
          mkdir -p upstream
          if git format-patch --stdout test_base > ci_fixes.patch; then
            cp ci_fixes.patch upstream/
          fi
      - uses: actions/upload-artifact@v3
        with:
          path: upstream
          name: upstream

  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-ubuntu-focal-standard-with-targets:dev
    needs: [get_ci_fixes]
    steps:
      - name: Update system packages
        run: |
          apt-get update && apt-get install -y git zip

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download upstream artifact
        uses: actions/download-artifact@v3
        with:
          path: upstream
          name: upstream

      - name: Apply CI fixes from sagemath/sage
        # After applying the fixes, make sure all changes are marked as uncommitted changes.
        run: |
          if [ -r upstream/ci_fixes.patch ]; then
            (cd worktree-image && git commit -q -m "current changes" --allow-empty -a && git am; git reset --quiet old; git add -N .) < upstream/ci_fixes.patch
          fi

      - name: Prepare
        run: |
          # Reuse built SAGE_LOCAL contained in the Docker image
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv --enable-download-from-upstream-url
      
      - name: Build docs
        id: docbuild
        run: make doc-html
        env:
          MAKE: make -j2 --output-sync=recurse
          SAGE_NUM_THREADS: 2

      - name: Copy docs
        id: copy
        run: |
          set -ex
          mkdir -p ./docs
          # Create changelog
          echo '## Preview of CHANGES.html'
          (cd /sage/local/share/doc/sage/html/en && git diff --name-only) | tee ./docs/CHANGES.txt
          (cd /sage/local/share/doc/sage/html/en && git diff; rm -rf .git) > ./docs/html.diff
          echo '## Preview of html.diff'; head -n 400 ./docs/html.diff
          (echo '<p><a href="html.diff">HTML diff</a>'; sed -E 's,(.*),<p><a href="\1">\1</a>,' ./docs/CHANGES.txt) > ./docs/CHANGES.html
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          # We also need to replace the symlinks because netlify is not following them
          cp -r -L /sage/local/share/doc/sage/html/en/* ./docs
          # Zip everything for increased performance
          zip -r docs.zip docs

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs.zip
