name: Build documentation

on:
  pull_request:
  push:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:dev
    env:
      CAN_DEPLOY: ${{ secrets.NETLIFY_AUTH_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          # Reuse built SAGE_LOCAL contained in the Docker image
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv --enable-download-from-upstream-url

      - name: Build
        run: make doc-html
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Copy docs
        if: env.CAN_DEPLOY == 'true'
        run: |
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          # We also need to replace the symlinks because netlify is not following them
          mkdir -p ./docs
          cp -r -L /sage/local/share/doc/sage/html/en/* ./docs

      - name: Deploy to Netlify production
        id: deploy-netlify
        if: env.CAN_DEPLOY == 'true'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs ${NETLIFY_PRODUCTION:+"--prod"}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_PRODUCTION: ${{ github.ref == 'refs/heads/develop' }}

      - name: Report deployment url
        if: env.CAN_DEPLOY == 'true'
        run: |
          echo "::notice::The documentation has being automatically deployed to Netlify. %0A ✅ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}"
